# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Movie.destroy_all
Character.destroy_all
Comment.destroy_all

#Movies
Movie.create(name: 'Spirited Away')
Movie.create(name: 'Nausicaä')
Movie.create(name: 'Ponyo')
Movie.create(name: 'My Neighbor Totoro')
Movie.create(name: 'Castle in the Sky')
Movie.create(name: 'KiKis Delivery Service')
Movie.create(name: 'Whisper of the Heart')
Movie.create(name: 'Princess Mononoko')
Movie.create(name: 'Howls Moving Castle')


#Characters
Character.create(name: 'No-Face (Kaonashi)', image_url: 'https://media.giphy.com/media/hXYlYBixtHEFq/giphy.gif', likes: 522, description: 'No-Face appeared in a semi-transparent state while shifting in and out of visibility. His organs are visible, pulsating in several states. His figure resembles that of a long, black tube. While it is unknown if No-Face has a physical body, it is shown that he can develop arms and legs with the capability of leaving footprints as he walks. An ominous, expressionless mask with grey-violet highlights is painted on his “head” of sorts, and while there is a “mouth” painted on the mask, No-Face has shown that his real, expertly-hidden mouth is larger than the one present on his mask.', movie_id: 1, quote: "Want some gold? I'm not giving it to anyone else.", abilities: 'Can ingest matter in all forms', species: 'Spirit', personality: 'He becomes extremely volatile after being fed.')
Character.create(name: 'Yubaba', image_url: 'https://i.pinimg.com/originals/f4/94/42/f494422486784cfc26c52ab79f2786d9.gif', likes: 76, description: 'Yubaba is the proprietor of The Bathhouse and the main antagonist of the Japanese animated film Spirited Away. She is the identical younger twin sister of Zeniba and the mother of Boh. She has a bird servant affectionately referred to by fans as Yu-Bird, an apprentice by the name of Haku, and is the employer of maybe hundreds of other bathhouse workers.', movie_id: 1, quote: "What did you do with my baby?!", abilities: 'Telekinesis, pyrokinesis, and flight', species: 'Witch', personality: 'As the main antagonist of the film, Yubaba has an extremely overbearing and intimidating personality. Like many other workers of her infamous bathhouse, Yubaba obsesses greedily over gold and is shown to be willing to view gold as a priority over her own family (especially Zeniba, whom she expresses hatred for). However, she has in some instances shown a great amount of motherly care for her son, Boh.')
Character.create(name: 'Chihiro Ogino (Sen)', image_url: 'https://uploads.disquscdn.com/images/630cf780327f5b8af854e044ee78df70f625f824e2f93915d455b074de7636e0.gif', likes: 11240, description: "Chihiro's growth into a capable individual is a core factor to the movement of Spirited Away's plot. During her adventure in the Spirit World, she matures from an easily-scared girl with a child-like personality to match her age to a hard-working, responsible, and brave young girl who has learned to put her fears aside for those she cares for.", movie_id: 1, quote: "They did turn into pigs. I wasn't dreaming.", abilities: 'N/A', species: 'Human', personality: 'In the beginning of the movie, Chihiro is shown to be a childish, easily-scared, and whiny girl. However, after her experiences at the Bathhouse and the Spirit World, she matures into a capable young adult.')
Character.create(name: 'Haku (Nigihayami Kohaku Nushi)', image_url: 'http://78.media.tumblr.com/4dd4a658754b20af9d4712640519d9b4/tumblr_na5mjiicwm1t89rpeo3_500.gif', likes: 146420, description: "Haku is Yubaba's apprentice and second-in-command at the Bathhouse. He seems to be a bit older than Chihiro, about 12 years old, although since he is the spirit of the Kohaku River, he is truly as old as his river is, which, in the Japanese version, is still flowing underneath the apartments now built over it.", movie_id: 1, quote: '"In the name of the wind and water within thee, unbind her."', abilities: 'As a river spirit, Haku possessed supernatural powers that are primarily associated with the element of water.', species: 'River Spirit/Dragon', personality: 'He can fly and seems to have the ability to change between his human and dragon form at will.')



Character.create(name: 'Nausicaä', image_url: 'https://media.giphy.com/media/JIpQ4eoE75M88/giphy.gif', likes: 1340, description: 'Nausicaä is the princess of the Valley of the Wind. She is the eleventh child of King Jhil, and the only one to live to maturity. She is rarely seen without her Mehve or her companion, Teto the fox-squirrel. Some believe her to be "The Blue Clad One" from Dorok legends.', movie_id: 2, quote: "It's so beautiful. It's hard to believe these spores could kill me.", abilities: 'Nausicaä has psychic powers, abilities which include telepathy, psychic force, when she repulses the slugworms, and communication with plants, when she talks to the Oldest Tree in the Valley.', species: 'Princess', personality: 'Nausicaä is 16 years old, but her wisdom is far beyond her young age. She has dedicated herself to help her people, including trying to find a cure for the miasma poison that so many suffer from. She is brave, courageous, wise, intelligent, loyal, honest, kind, compassionate, and everything that one looks for in a true heroine. She stands tall against all adversaries and is willing to sacrifice her life in order to save those around her.')
Character.create(name: 'Asbel', image_url: 'https://thumbs.gfycat.com/PerfectLameEidolonhelvum-size_restricted.gif', likes: 50, description: 'Asbel is the son of the Chieftain of Pejitei, in the lands of the Autonomous States of the Periphery.', movie_id: 2, quote: "Why does everything that's good for you have to taste so bad?", abilities: 'N/A', species: 'Prince', personality: 'Asbel uses "being shamed" as an euphemism for rape. Asbel expressed his relief that the Imperial Guard "just" killed Rastel during the attack on Pejitei and did not shame her.')



Character.create(name: 'Ponyo', image_url: 'https://media.giphy.com/media/zPd1djgJBL7So/giphy.gif', likes: 75432, description: 'Ponyo (ポニョ, Ponyo), born Brunhilde (ブルンヒルデ, Burunhirude) is one of the main protagonists of the film Ponyo on the Cliff by the Sea directed by Hayao Miyazaki. She is a magical fish descended from the Sea Goddess.', movie_id: 3, quote: 'Ponyo loves Sosuke! I will be a human too!', abilities: 'Ponyo gladly gave up her magical abilities to become human and stay with Sosuke.', species: 'Demi-god', personality: "She behaves just like a regular five-year-old, intelligent, adorable, and mischievous, and later in the movie, sleepy. She's very happy and sweet all the time.")
Character.create(name: 'Sōsuke', image_url: 'http://24.media.tumblr.com/ac52d03f6293ea65660a4a0a9030bed0/tumblr_mjw30cvd4e1ra5a63o1_500.gif', likes: 55542, description: "Sōsuke (さすけ, Sosuke) is one of the main protagonists of the film Ponyo on the Cliff by the Sea directed by Hayao Miyazaki. He is the son of Koichi and Lisa, as well as Ponyo's lover.", movie_id: 3, quote: "Mom! Ponyo came back, and she's a little girl now!", abilities: 'N/A', species: 'Human', personality: "Sosuke is depicted as intelligent, loyal, heroic. He is based on Hayao Miyazaki's son Garo Miyazaki, when he was five years old.")
Character.create(name: 'Granmammare', image_url: 'http://24.media.tumblr.com/ac52d03f6293ea65660a4a0a9030bed0/tumblr_mjw30cvd4e1ra5a63o1_500.gif', likes: 5401, description: "Granmammare is enormous, possibly as big, if not bigger than a Blue Whale. She is able to change shape and size, and also appears to glow with a warm, golden light.", movie_id: 3, quote: "I understand.", abilities: 'In the film she is the most powerful creature in the world. She can use her power without messing up the environment. She is able to change shape and size of her body. She can also read the mind by touching someone. So she could read Fujimotos mind in a short time by touching his head.', species: 'Deities', personality: "Granmammare is patient and unwaveringly kind.")
Character.create(name: 'Lisa', image_url: 'http://down.57gif.com/down/2m/480852', likes: 33425, description: "She is the mother of Sosuke and wife of Kōichi and foster mother of Ponyo.", movie_id: 3, quote: 'Youll do the right thing. I know it. Youre only five, but youre very smart. Sometimes we take a leap. Be brave. You can do it while you can.', abilities: 'Being a supermom.', species: 'human', personality: "She is independent and warm.")



Character.create(name: 'Totoro', image_url: 'https://media.giphy.com/media/IRna46BPHozja/giphy.gif', likes: 53222, description: "Totoro is the title tetartagonist and forest spirit that lives in the largest camphor tree in a small village. He is featured in Studio Ghibli's film My Neighbor Totoro.", movie_id: 4, quote: 'N/A', abilities: 'They seem to have magical abilities and at least some control over plants.', species: 'Totoro (Forest Spirit)', personality: "They're known to be friendly towards children and have also been described as being 'Keepers of the Forest'.")
Character.create(name: 'Satsuki Kusakabe', image_url: 'https://i.gifer.com/2ICo.gif', likes: 432, description: 'Satsuki (also known as Satsuko) is the second protagonist of My Neighbor Totoro. She is the older sister of Mei in My Neighbor Totoro.', movie_id: 4, quote: 'Come out, come out, wherever you are!', abilities: 'N/A', species: 'Human', personality: 'Satsuki likes to think of herself as grown-up and caring for her sister. She is very lively, although not quite as lively as Mei. Satsuki is a good sister on the whole and looks after Mei to the best of her ability despite being upset about their ill mother. She is also very kind and responsible overall.')


Character.create(name: 'Sheeta', image_url: 'https://i.pinimg.com/originals/56/48/76/564876496e1949a9f80a79aba880d277.gif', likes: 35225, description: "Sheeta wears a plain, indigo dress with white petticoat underneath until she changed into Dola's large pink pants and yellow blouse and brown slip-on shoes. She has brown hair with short bangs in the front and wears her hair in two braids on either side of her head. Her eyes are blue and grey. She also sports a red hairband. Each braid is tied neatly at the bottom with red ribbon, a common color for hair accessories in Studio Ghibli films. ", movie_id: 5, quote: 'A king without compassion does not deserve a kingdom. No matter how many weapons you may have, no matter how great your technology might be, the world cannot live without love.', abilities: 'She possesses an aetherium crystal which can save her in times of danger.', species: 'Human', personality: "Sheeta is reserved, somewhat aloof to strangers, and quiet. ")
Character.create(name: 'Gardener Robot', image_url: 'https://media.giphy.com/media/vwoy7ihVltOrC/giphy.gif', likes: 44315, description: "The robot has a dome-shaped head with uneven eyes; the left eye is about twice the size of the right eye. They can shoot very destructive lasers of varying force from their eyes. They appear to be made out of a dark metal, and they have the crest of the royal family of Laputa on their chests.", movie_id: 5, quote: '*Stares softly*', abilities: 'Takes care of wildlife.', species: 'Robot', personality: "The robot is kind and gentle to the children.")
Character.create(name: 'Kiki', image_url: 'https://media.giphy.com/media/sUB72TNhjzW5G/source.gif', likes: 4322, description: "", movie_id: 6, quote: 'Im gonna be the very best witch that I can be, Mom. And I know having a good heart is important.	', abilities: 'None at the moment, she is still training.', species: 'Witch', personality: "Kiki is a strong-willed and cute 13-year-old, leaving home for a year in order to train as a witch. She is very friendly, sweet, and upbeat, however is rather stubborn at times and proud, which is sometimes to her disadvantage.")
Character.create(name: 'Jiji', image_url: 'https://media.giphy.com/media/NRGPhhZ5kLThu/giphy.gif', likes: 54343, description: "A black cat.", movie_id: 6, quote: 'Meow.', abilities: 'Eating, sleeping, being around Kiki', species: 'Cat', personality: "Loyal")
Character.create(name: 'Senior Witch', image_url: 'https://thumbs.gfycat.com/NeglectedMeekKitty-small.gif', likes: 53, description: "Senior Witch is possibly 13 years old like Kiki. She has light brown hair with two plaits and teal eyes. She wears a purple dress, two heart shaped gold earrings, and a red necklace. Her broomstick is brown, and she flies with a black cat with radiant green eyes and a lantern.", movie_id: 6, quote: 'Since my skill is fortune telling, I can handle anything... I tell fortunes about love. And what exactly is your skill?', abilities: 'Fortune telling', species: 'Witch', personality: "Sassy")


Character.create(name: 'Shizuku Tsukishima', image_url: 'https://data.whicdn.com/images/244179943/original.gif', likes: 0, description: "Shizuku Tsukishima is a slender girl, fourteen years old, with short brown hair and black eyes. At the start of the movie, she is seen wearing a buttoned yellow shirt and yellow skirt along with it. Later however, she wears a red shirt with a white collar, a yellow skirt and a flat straw hat with a purple band around it.", movie_id: 7, quote: 'Youre the one who inspired me, Seiji. Im glad I pushed myself. I know myself a little bit better now.', abilities: 'Working Hard.', species: 'Human', personality: "Hardworking and shy.")


Character.create(name: 'TicTics', image_url: 'https://media.giphy.com/media/oktW1eBGpHOoM/giphy.gif', likes: 0, description: "", movie_id: 8, quote: '', abilities: '', species: '', personality: "")
Character.create(name: 'Spirit of the Forest', image_url: 'https://data.whicdn.com/images/32547432/original.gif', likes: 0, description: "The Forest Spirit looks like a deer, but with more antlers and a human face; He can transform into a gigantic semi-translucent humanoid during the night, called the Night-Walker.", movie_id: 8, quote: 'N/A', abilities: 'Gives and takes life', species: 'God', personality: "A good spirit")
Character.create(name: 'Forest Spirit', image_url: 'https://data.whicdn.com/images/92889002/original.gif', likes: 0, description: "The Forest Spirit looks like a deer, but with more antlers and a human face; He can transform into a gigantic semi-translucent humanoid during the night, called the Night-Walker.", movie_id: 8, quote: 'N/A', abilities: 'Gives and takes life', species: 'God', personality: "A good spirit")


Character.create(name: 'Sophie Hatter', image_url: 'http://25.media.tumblr.com/d01a40a3e9e7dd204a08e87b3433086f/tumblr_mire58wJKG1qzuse1o1_500.gif', likes: 32455, description: 'Sophies appearance in the movie depicts her as a young innocent looking girl with brown eyes and long brown hair, which she wears in a plait down her back.', movie_id: 9, quote: 'I hope you burn your bacon.', abilities: 'Turns into a 90 years old woman', species: 'Witch of the East', personality: 'Though Sophie is initially reserved and lacking confidence, she demonstrates herself to be a strong-minded individual after she is transformed into an old woman, becoming less afraid of what others think of her. Dutiful, kind, and considerate, Sophie also has a tendency to be impulsive in her actions and often feels guilty when she does something wrong, though her attempts to rectify matters are usually disastrous. She also is very compassionate and tries to help others, no matter who they are, going so far as taking the Witch of the Waste under her protection.')
Character.create(name: 'Claud', image_url: 'https://i.pinimg.com/originals/7a/ea/ff/7aeafff8c9ad731abbe51f5b67f0a2b3.gif', likes: 0, description: "Fire", movie_id: 9, quote: 'You old hag.', abilities: 'Can become bigger.', species: 'Demon', personality: "Nice.")
Character.create(name: 'Young Howl Jenkins Pendragon', image_url: 'https://i.pinimg.com/originals/39/98/eb/3998ebf4d1de28e79302819bcbbfa325.gif', likes: 0, description: "Black hair", movie_id: 9, quote: 'N/A', abilities: 'None', species: 'Human', personality: "Kind and giving.")
Character.create(name: 'Night Crawlers', image_url: 'https://66.media.tumblr.com/5538c41cf8b43ce4b923b5e71d2c10ec/tumblr_o76hkiU9DD1v557xao1_500.gif', likes: 0, description: "Black blobs", movie_id: 9, quote: 'N/A', abilities: 'Takes away life', species: 'Night Crawlers', personality: "Deadly")
Character.create(name: 'Howl Jenkins Pendragon', image_url: 'https://data.whicdn.com/images/302979492/original.gif', likes: 0, description: 'Howl has shoulder-length straight light blonde hair, light blue eyes, and a pale complexion. He is tall and slender.', movie_id: 9, quote: 'Sorry, Ive had enough of running away, Sophie. Now Ive got something I want to protect. Its you.', abilities: 'Can change into different animals', species: 'Wizard', personality: 'Howl has a kind, generous personality. He allowed Michael and Sophie to live with him, and is very forgiving of their mistakes. He also gave Calcifer his heart when Calcifer was a dying falling star. His good traits, however, are masked by his more negative traits, as well as deliberate "blackening of his name", so very few people know of them. He hates to quarrel, and will "slither out" of situations he doesnt want to be in. He hates to be pinned down to anything, and is quite cowardly.')



#Comments
Comment.create(character_id: 7, content: "Ponyo is so sweet! She's my favorite Studio Ghibli character.", username: 'jennyjean')
Comment.create(character_id: 7, content: "Ponyo and Sosuke's friendship is so innocent and pure.", username: 'jennyjean')
Comment.create(character_id: 7, content: "I'd love to see more Demi-god character-types in these films.", username: 'frank')
Comment.create(character_id: 7, content: "I love how the illustrators show Ponyo's metamorphosis!", username: 'joe123')
Comment.create(character_id: 7, content: 'Ponyo is the most endearing character.', username: 'jennyjean')
